import Head from 'next/head'
import dynamic from "next/dynamic";
import { Suspense } from "react";



import styles from '../styles/Home.module.css'
import Hero from './Hero';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Hero/>
      </main>
    </div>
  )
}
