import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Content from './Content'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Content />
      </main>
    </div>
  )
}
